### ISSUE TITLE
Iteration Based Progress

### ISSUE THREAD

**Issue by criteriamor** [francepack/trapper-keeper-ui#1]
Divide spec into iterable chunks

**Comment by criteriamor** [comment]
Still need backend

**Comment by taylorsperry** [comment]
DTR: 

Template for DTR Memo

### Project:

#### Group Member Names: Mason France, Edgar Munoz, Taylor Sperry

#### Goals and Expectations for the Project (What does each group member hope to get out of this project? What do we want to achieve as a team? How will we know that we're successful?):

-Taylor: Feel more confident w/testing. Be more conscientious about TDD. Learn Thunks.

-Mason: Feel good about finished product, all facets touched on

-Edgar: Have completed project w/at least 50 tests passing. I want to help everyone learn at something they feel weakest at.

#### Team strengths & collaboration styles (consider discussing your Pairin qualities here):

-Taylor: Can f**king crank, Start w/d+n and then phasing into delegation

-Mason: Strategic thinker, good ideas, likes focused tasks. Consensus based.

-Edgar: Focused research, Flexible

#### How we can use our strengths to overcome obstacles:

Taylor: Staying focused

Mason: Github issues

Edgar: Redux/React console

#### Schedule Expectations (When are we available to work together and individually? What constraints do we have?):

Taylor: Open

Mason: Rehearsals Sunday nights

Edgar: Available

#### Communication Expectations (How and often will we communicate? How do we keep lines of communication open? How will we make decisions as a team?):

Taylor: Slack, Use communication for team-based problem-solving

Mason: Slack Call/Screen Share?, will try to reach out more

Edgar: Available on slack, other mediums on ask

#### Abilities & Growth Expectations (Technical strengths and areas for desired improvement):

Taylor: Testing, Thunks, Demystify Backend

Mason: Thunks, 

Edgar: Streamline implementation of a React/Redux/Router/Testing project w/Thunks

#### Workload Expectations (What features do we each want to work on?):

Taylor: Everyone has a hand in each part

Mason: Delegation/Cooperation through intentional planning + consistency

Edgar: Expect to work a lot. Doesn’t want to fizzle out towards tail-end. 

#### Workflow Expectations (Git workflow/Tools/Code Review/Reviewing Pull Requests/Debugging and Problem-solving Techniques):

Taylor: communicative of pull requests content

Mason: more meticulous branching

Edgar: micro-commits, issues, (checkpoints), show team how to use vscode for commits

#### Expectations for giving and receiving feedback:

Taylor: nicely tell her she’s being grouchy

Mason: supportive, gentle nudging

Edgar: not personal(for me)

#### Project management tools we will use:

Issues, checkpoints, google doc/trello for tracking and planning

#### Day 1 Agenda: 

Edgar: Research, prep

Taylor: Initial setup, some pseudo coding

#### Additional Notes: Don’t push to master (unless all are present), pair w/mod 4, ask classmates for help
